[project]
name = "epymorph"

version = "0.0.0"

authors = [
  { name = "Tyler Coles", email = "tyler.coles@nau.edu" },
  { name = "Frank Burkhart" },
  { name = "Alex Nez" },
  { name = "Trevor Johnson" },
  { name = "Jarom Craghead" },
  { name = "Ajay Shyam Pasam" },
  { name = "Sindhura Paruchuri" },
  { name = "Izaac Molina" },
  { name = "Meaghan Freund" },
]

description = "EpiMoRPH disease modeling"

readme = "README.md"

requires-python = ">=3.11"

# license = ""

keywords = ["epidemiology", "disease modeling", "metapopulation"]

classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent",
  "Intended Audience :: Science/Research",
  "Topic :: Scientific/Engineering :: Bio-Informatics",
  "Typing :: Typed",
]

dependencies = [
  "matplotlib~=3.9.0",
  "numpy~=1.26.4",
  "sympy~=1.12.1",
  "psutil~=5.9.8",
  "pandas[excel]~=2.2.2",
  "geopandas~=0.14.4",
  "census~=0.8.22",
  "jsonpickle~=3.2.1",
  "platformdirs~=4.2.2",
  "graphviz~=0.20.3",
  "typing_extensions~=4.12.2",
  "ipython~=8.26.0",
]

[project.optional-dependencies]
dev = [
  "autopep8~=2.0.4",
  "isort~=5.13.2",
  "ipykernel~=6.29.4",
]

[project.scripts]
epymorph = "epymorph.__main__:main"

[tool.autopep8]
max_line_length = 88
ignore = ["E731"]

[tool.isort]
skip_glob = [".venv*/*"]

[tool.pyright]
exclude = [
  "**/__pycache__",
  "**/.*",
  "build",
]
# Pyright doesn't seem to be able to handle sympy operators,
# so until that's fixed ignore operator errors.
reportOperatorIssue = "none"

[tool.pylint.basic]
max-line-length = 120
good-names = ["T", "N", "C", "E"]
good-names-rgxs = ["[a-z_][a-zA-Z0-9_]*"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["epymorph*"]

[tool.setuptools.package-data]
"epymorph" = ["py.typed"]
