"""epymorph's collection of built-in compartment models."""

from epymorph.data.ipm.no import No
from epymorph.data.ipm.pei import Pei
from epymorph.data.ipm.seirs import Seirs
from epymorph.data.ipm.sirh import Sirh
from epymorph.data.ipm.sirs import Sirs
from epymorph.data.ipm.sparsemod import Sparsemod

### WARNING ##########################################
# This file is generated by the data_exports script. #
# Manual changes to this file will be lost.          #
######################################################

__all__ = [
    "No",
    "Pei",
    "Seirs",
    "Sirh",
    "Sirs",
    "Sparsemod",
]
