# Runs automated canary tests

# These tests perform minimal checks to validate that our integration with an external
# service is still valid. We want these tests to be as small as possible and rare so that we
# minimize excess traffic on our partners. However we also don't want ADRIOs (for example)
# to start failing without us noticing. So it's a trade-off.

name: Canary test

on:
  workflow_dispatch:
  schedule:
    - cron: "0 16 1 * *" # 1st of every month, 9AM Arizona

jobs:
  canary-test:
    name: Canary matrix
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0
        with:
          enable-cache: true
          version: ${{ vars.UV_VERSION }}

      - name: Install dependencies
        run: uv sync --frozen --all-extras --dev

      - name: Run canary tests
        env:
          CENSUS_API_KEY: ${{ secrets.CENSUS_API_KEY }}
        run: uv run pytest tests/canary
