# Perform dependency review on PRs to identify problems with dependencies.
# See: https://github.com/actions/dependency-review-action

name: Dependency Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '.github/workflows/*.yml'
      - 'pyproject.toml'
      - 'uv.lock'

permissions: {}

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # for actions/checkout
      pull-requests: write  # for actions/dependency-review-action
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: low
          fail-on-scopes: runtime, development
          comment-summary-in-pr: on-failure
          show-patched-versions: true
